[package]
name = "bb_save_access"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.50"
aes="0.7.4"
block-modes="0.8.1"
base64 = "0.21.0"
serde_json = "1.0.96"
